### ISSUE TITLE
integration tests to self tests

### ISSUE THREAD

**Issue by lrnzcig** [datakind/Data-Observation-Toolkit#28]
After PR #19 is merged, adding integration tests becomes low hanging fruit.

The test [test_run_dot_tests](https://github.com/datakind/Data-Observation-Toolkit/blob/test-demo-dataset/dot/self_tests/unit/test_run_dot_tests.py) runs the full DOT pipeline for the demo sample dataset. Adding checks to the results would make unnecessary to run the regression tests that we used in the legacy DOT repo.

Additionally, the following tests should not run the full DOT pipeline:
- `test_dbt_log_safe.py`
- `test_utils.py`
- `test_utils_schema_improved.py`
but only the steps that are actually under test.

**Comment by dividor** [comment]
Hi @lrnzcig,

Thanks so much for  PR #19, it's now merged.

Go for the low-hanging fruit!
