### ISSUE TITLE
The demo data build should include all test types

### ISSUE THREAD

**Issue by dividor** [datakind/Data-Observation-Toolkit#4]
**Describe your maintenance task**
The [demo data build](https://github.com/datakind/Data-Observation-Toolkit/blob/main/db/dot/4-upload_sample_dot_data.sql) currently doesn't include all test types, one or two are missing. So we can use the demo data for automatic regression tests, we should add these.

**Additional context**

**Comment by dividor** [comment]
Hi @lrnzcig,

If you fancied taking a look at this, that would be fantastic.

Thanks,
Matt

**Comment by lrnzcig** [comment]
sure, self-assigned!

**Comment by lrnzcig** [comment]
following test types are missing
- custom_sql
- possible_duplicate_forms
- associated_columns_not_null
- expression_is_true
