### ISSUE TITLE
Remove unnecessary packages from requirement_dot.txt

### ISSUE THREAD

**Issue by dividor** [datakind/Data-Observation-Toolkit#53]
**Describe your maintenance task**
There are a lot of packages which aren't used in [./dot/requirements_dot.txt](./dot/requirements_dot.txt) adding to dependency load. We should remove them if not used.

**Additional context**
Be sure to keep anything which dot, linting/black or self tests need.

**Comment by JanPeterDatakind** [comment]
Implemented in release 1.0.5
